name: ManagerXL
version: 0.4.1
main: com.dre.managerxl.P
authors: [Frank Baumann, Tobias Schmitz, Joscha Schmitz]
softdepend: [Vault]
commands:
 ban:
  description: Ban a Player
 unban:
  description: Unban a Player
 timeban:
  description: Ban a Player for a specific time
 home:
  description: Takes you to your Home
 sethome:
  description: Set your Home
 kick:
  description: Kick a player
 kickall:
  description: Kick all players
 mute:
  description: Un/Mute a player
 gamemode:
  aliases: [gm]
  description: Set the GameMode of a player
 invisible:
  aliases: [inv]
  description: Set the visibility of a player
 motd:
  description: Show the MotD of the server
 motdset:
  aliases: [motds]
  description: Set the MotD of the server
 addbroadcast:
  aliases: [addbroad]
  description: Add Broadcast the servers Broadcaster
 addnews:
  description: Add News the servers Broadcaster
 adddate:
  aliases: [addevent]
  description: Add Date/Event the servers Broadcaster