name: ManagerXL
version: 0.1
main: com.dre.managerxl.P
authors: [Frank Baumann, Tobias Schmitz, Joscha Schmitz]
softdepend: [Vault]
commands:
 ban:
  description: Ban a Player
 unban:
  description: Unban a Player
 timeban:
  description: Ban a Player for a specific time
 home:
  description: Takes you to your Home
 sethome:
  description: Set your Home
 kick:
  description: Kick a player
 kickall:
  description: Kick all players
 mute:
  description: Un/Mute a player
 gamemode:
  aliases: [gm]
  description: Set the GameMode of a player